import {
    AuthSession,
    Category,
    Product,
    ProductHistory,
    ProductReview,
    ProductToSeller,
    ProxySetting,
    Seller,
    User,
    UserAgent,
    Log,
    ProductRequest,
    EmailVerification,
} from './entities';

export const entites = [
    AuthSession,
    Category,
    Product,
    ProductHistory,
    ProxySetting,
    ProductReview,
    Seller,
    ProductToSeller,
    UserAgent,
    User,
    Log,
    ProductRequest,
    EmailVerification,
];
